development:
  adapter: postgresql
  encoding: unicode
  database: emojiapp_development
  pool: 5
  username: emojiapp
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: emojiapp_test
  pool: 5
  username: emojiapp
  password: password1

production:
  <<: *default
  database: emoji2emoji
  username: god
  password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>
