# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

Prompt.create(prompt: "rodeo")
Prompt.create(prompt: "academia")
Prompt.create(prompt: "action movie")
Prompt.create(prompt: "gym")
Prompt.create(prompt: "horror film")
Prompt.create(prompt: "family vacation")
Prompt.create(prompt: "first date")
Prompt.create(prompt: "job hunt")
Prompt.create(prompt: "sci fi movie")
Prompt.create(prompt: "monser flick")
Prompt.create(prompt: "alien invasion")
Prompt.create(prompt: "puberty")
Prompt.create(prompt: "alchemy")
Prompt.create(prompt: "playground")
Prompt.create(prompt: "school")
Prompt.create(prompt: "college")
Prompt.create(prompt: "animal cakes")
Prompt.create(prompt: "trippy dance party")
Prompt.create(prompt: "action news")
Prompt.create(prompt: "jane austen")
Prompt.create(prompt: "star trek")
Prompt.create(prompt: "camping")
Prompt.create(prompt: "meal")
Prompt.create(prompt: "caberet")
Prompt.create(prompt: "birthday party")
Prompt.create(prompt: "bob ross")
Prompt.create(prompt: "picard maneuver")
Prompt.create(prompt: "minstry of propaganda")
Prompt.create(prompt: "lisa frank stubs her toe")
Prompt.create(prompt: "woodstock")
Prompt.create(prompt: "seinfeld")
Prompt.create(prompt: "friends")
Prompt.create(prompt: "bar")
Prompt.create(prompt: "sesame street")
Prompt.create(prompt: "mr. roger's neighborhood")
Prompt.create(prompt: "advertisement")
Prompt.create(prompt: "darwin awards")
Prompt.create(prompt: "board room")
Prompt.create(prompt: "murder most fowl")
Prompt.create(prompt: "favorite tim curry")
Prompt.create(prompt: "shakespeare")
Prompt.create(prompt: "haiku")
Prompt.create(prompt: "disney movie")
Prompt.create(prompt: "star wars planet")
Prompt.create(prompt: "saturday morning cartoon")
Prompt.create(prompt: "cozy time")
Prompt.create(prompt: "-- do you even riff, bro?")